run:
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - goheader
    - goimports
    - gosec
    - gosimple
    - lll
    - nakedret
    - revive
    - stylecheck
  presets:
    - bugs
    - unused

linters-settings:
  goheader:
    template: |-
      SPDX-License-Identifier: MIT
  goimports:
    local-prefixes: github.com/xen0n/goubao
  gosimple:
    go: '1.17'
  lll:
    line-length: 120
    tab-width: 4
  nakedret:
    max-func-lines: 1
  stylecheck:
    go: '1.17'
